# __GL_THREADED_OPTIMIZATIONS=0  reaper -new
__GL_THREADED_OPTIMIZATIONS=0 __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS="--no-sandbox --disable-gpu" reaper

